### PR TITLE
Nearest station CSV endpoint improvements

### PR DESCRIPTION
**Pull request by joefutrelle**
* Allow user to specify the following in URL parameters:
  * `timestamp_column`
  * `latitude_column`
  * `longitude_column`
  
 * Return CSV with original column names plus:
   * `nearest_station`
   * `distance_km`

### CODE REVIEW

**Review by joannekoch — COMMENTED** [review]
1. `if {'nearest_station', 'distance_km'}.issubset(df.columns):` checks if both columns are present but it should check if at least one column is present. 

    If only nearest_station or distance_km is present in the csv file, this error is thrown: 
    {"error":"Length mismatch: Expected axis has 7 elements, new values have 8 elements"}

2. Currently the uploaded csv file can contain latitude values outside of the valid range of -90 and +90, and longitude values outside of the valid range of -180 and 180. Please add range checking.

**Comment by joefutrelle** [comment]
@joannekoch should be ready for review now

**Review by joannekoch — COMMENTED** [review]
For the nearest-station-csv endpoint, the lat/long range check also needs to be added to add_nearest_station.

**Review by joannekoch — APPROVED** [review]
Nice work!

**Pull request merged**
